global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: "some_target_mail"
        from: "some_gmail"
        smarthost: smtp.gmail.com:587
        auth_username: "some_gmail"
        auth_identity: "some_gmail"
        auth_password: "some_password"
        send_resolved: true