{
 "title": "Spring App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Spring App Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"st-testing-application:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"st-testing-application:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spring CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"st-testing-application:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Frequency",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Rate Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"RequestRate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wrong Endpoint Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"Wrong Endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Found Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"Not found\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wrong Method Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"Wrong Method\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}