groups:
  - name: default
    rules:
      - alert: RequestRate
        expr: rate(http_server_requests_seconds_count{uri="/actuator"}[1m]) > 0
        for: 1m
        annotations:
          summary: 'Application receiving too many requests'
        labels:
          severity: 'critical'
      - alert: Wrong Method
        expr: rate(http_server_requests_seconds_count{status=~"405"}[1m]) > 0
        for: 1s
        annotations:
          summary: 'Application received wrong request type'
        labels:
          severity: 'critical'
      - alert: Not found
        expr: rate(http_server_requests_seconds_count{status=~"404"}[1m]) > 0
        for: 1s
        annotations:
          summary: 'Requested endpoint did not exist'
        labels:
          severity: 'critical'

  - name: AllInstances
    rules:
      - alert: InstanceDown
        # Condition for alerting
        expr: up == 0
        for: 1m
        # Annotation - additional informational labels to store more information
        annotations:
          title: 'Instance {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
        # Labels - additional labels to be attached to the alert
        labels:
          severity: 'critical'